---
name: semantic-release your GitHub Action
description: GitHub Action to semantically release your GitHub Action
author: EricCrosson
branding:
  icon: package
  color: orange

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Fetch all history and tags for calculating next semantic version
        fetch-depth: 0

    - name: Install is-semantic-release-configured
      uses: taiki-e/install-action@v2
      with:
        tool: is-semantic-release-configured@1

    - run: |
        : configure semantic-release
        if ! is-semantic-release-configured; then
          rm -f package.json package-lock.json
          cp ${{ github.action_path }}/package.json package.json
          cp ${{ github.action_path }}/package-lock.json package-lock.json
          cp ${{ github.action_path }}/.releaserc.json .releaserc.json
        fi
      shell: bash

    - name: Configure Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: npm

    - name: Cache npm dependencies
      uses: actions/cache@v3
      id: cache-node-modules
      with:
        path: node_modules
        key: semantic-release-your-github-action-${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

    - if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: |
        : install semantic-release
        npm ci --ignore-scripts --loglevel error
      shell: bash

    - run: |
        : invoke semantic-release
        ./node_modules/.bin/semantic-release --repository-url ${url/git/https}
      env:
        GITHUB_TOKEN: ${{ github.token }}
        url: ${{ github.repositoryUrl }}
      shell: bash

      # DISCUSS: do we want to restore the original configuration file and
      # package manifests?
      #
      # We'll omit for now, relying on the assumption that we're the only
      # thing running in the calling workflow.
      #
      # If you have a different use case, please open an issue or submit a PR!
